"""Jira service for ticket creation and management."""

from typing import Any

import httpx

from app.config import settings
from app.models.types import ActionItem
from app.repositories import jira_ticket_repository
from app.utils.logger import get_logger
from app.utils.retry import async_retry

logger = get_logger(__name__)


class JiraService:
    """Service for Jira API interactions."""

    def __init__(self) -> None:
        """Initialize Jira service."""
        self._base_url = f"https://{settings.jira_host}/rest/api/3"
        self._auth = (settings.jira_email, settings.jira_api_token)

    @async_retry(max_attempts=3)
    async def create_ticket(
        self,
        project_key: str,
        summary: str,
        description: str,
        issue_type: str = "Task",
        priority: str | None = None,
        assignee_account_id: str | None = None,
        due_date: str | None = None,
        labels: list[str] | None = None,
        custom_fields: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create a Jira ticket.

        Args:
            project_key: Jira project key
            summary: Ticket summary/title
            description: Ticket description
            issue_type: Type of issue (Task, Bug, Story, etc.)
            priority: Priority level
            assignee_account_id: Jira account ID of assignee
            due_date: Due date in YYYY-MM-DD format
            labels: List of labels
            custom_fields: Additional custom fields

        Returns:
            Created issue data
        """
        logger.info("Creating Jira ticket", project=project_key, summary=summary[:50])

        # Build issue fields
        fields: dict[str, Any] = {
            "project": {"key": project_key},
            "summary": summary,
            "description": {
                "type": "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": description}],
                    }
                ],
            },
            "issuetype": {"name": issue_type},
        }

        if priority:
            fields["priority"] = {"name": priority}

        if assignee_account_id:
            fields["assignee"] = {"accountId": assignee_account_id}

        if due_date:
            fields["duedate"] = due_date

        if labels:
            fields["labels"] = labels

        if custom_fields:
            fields.update(custom_fields)

        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{self._base_url}/issue",
                auth=self._auth,
                headers={"Content-Type": "application/json"},
                json={"fields": fields},
            )
            response.raise_for_status()

            issue = response.json()
            logger.info(
                "Created Jira ticket",
                key=issue.get("key"),
                id=issue.get("id"),
            )
            return issue

    async def create_ticket_from_action_item(
        self,
        meeting_id: str,
        action_item: ActionItem,
        project_key: str,
        meeting_topic: str | None = None,
    ) -> dict[str, Any] | None:
        """Create Jira ticket from action item with deduplication.

        Args:
            meeting_id: Meeting identifier
            action_item: Action item to create ticket for
            project_key: Jira project key
            meeting_topic: Optional meeting topic for context

        Returns:
            Created issue data or None if already exists
        """
        # Check for duplicate
        if await jira_ticket_repository.exists(
            meeting_id,
            action_item.task,
            action_item.owner_name,
        ):
            logger.info(
                "Ticket already exists for action item",
                meeting_id=meeting_id,
                task=action_item.task[:50],
            )
            return None

        # Map priority
        priority_map = {
            "HIGH": "High",
            "MEDIUM": "Medium",
            "LOW": "Low",
        }
        priority = priority_map.get(action_item.priority, "Medium")

        # Find assignee
        assignee_id = None
        if action_item.owner_email:
            user = await self.find_user_by_email(action_item.owner_email)
            if user:
                assignee_id = user.get("accountId")

        # Build description
        description = f"""
Action item from meeting: {meeting_topic or 'Team Meeting'}

Task: {action_item.task}
Assigned to: {action_item.owner_name}
Priority: {action_item.priority}
{f"Context: {action_item.context}" if action_item.context else ""}

---
This ticket was auto-generated by AI Meeting Bot.
        """.strip()

        labels = ["meeting-action-item", "auto-generated"]

        issue = await self.create_ticket(
            project_key=project_key,
            summary=action_item.task[:200],  # Jira summary limit
            description=description,
            issue_type="Task",
            priority=priority,
            assignee_account_id=assignee_id,
            due_date=action_item.deadline,
            labels=labels,
        )

        # Save to repository
        await jira_ticket_repository.save(
            meeting_id=meeting_id,
            task=action_item.task,
            owner_name=action_item.owner_name,
            jira_key=issue.get("key", ""),
            jira_id=issue.get("id", ""),
        )

        return issue

    @async_retry(max_attempts=2)
    async def find_user_by_email(self, email: str) -> dict[str, Any] | None:
        """Find Jira user by email.

        Args:
            email: User's email address

        Returns:
            User data or None
        """
        logger.info("Looking up Jira user", email=email)

        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self._base_url}/user/search",
                auth=self._auth,
                params={"query": email},
            )
            response.raise_for_status()

            users = response.json()
            if users:
                return users[0]
            return None

    @async_retry(max_attempts=2)
    async def get_issue(self, issue_key: str) -> dict[str, Any]:
        """Get Jira issue details.

        Args:
            issue_key: Issue key (e.g., PROJ-123)

        Returns:
            Issue data
        """
        logger.info("Fetching Jira issue", key=issue_key)

        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self._base_url}/issue/{issue_key}",
                auth=self._auth,
            )
            response.raise_for_status()
            return response.json()

    @async_retry(max_attempts=2)
    async def update_issue(
        self,
        issue_key: str,
        fields: dict[str, Any],
    ) -> None:
        """Update Jira issue.

        Args:
            issue_key: Issue key
            fields: Fields to update
        """
        logger.info("Updating Jira issue", key=issue_key)

        async with httpx.AsyncClient() as client:
            response = await client.put(
                f"{self._base_url}/issue/{issue_key}",
                auth=self._auth,
                headers={"Content-Type": "application/json"},
                json={"fields": fields},
            )
            response.raise_for_status()

        logger.info("Updated Jira issue", key=issue_key)

    @async_retry(max_attempts=2)
    async def add_comment(
        self,
        issue_key: str,
        comment: str,
    ) -> dict[str, Any]:
        """Add comment to Jira issue.

        Args:
            issue_key: Issue key
            comment: Comment text

        Returns:
            Created comment data
        """
        logger.info("Adding comment to Jira issue", key=issue_key)

        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{self._base_url}/issue/{issue_key}/comment",
                auth=self._auth,
                headers={"Content-Type": "application/json"},
                json={
                    "body": {
                        "type": "doc",
                        "version": 1,
                        "content": [
                            {
                                "type": "paragraph",
                                "content": [{"type": "text", "text": comment}],
                            }
                        ],
                    }
                },
            )
            response.raise_for_status()

            data = response.json()
            logger.info("Added comment", comment_id=data.get("id"))
            return data

    @async_retry(max_attempts=2)
    async def transition_issue(
        self,
        issue_key: str,
        transition_name: str,
    ) -> bool:
        """Transition Jira issue to new status.

        Args:
            issue_key: Issue key
            transition_name: Name of transition (e.g., "Done", "In Progress")

        Returns:
            True if successful
        """
        logger.info("Transitioning Jira issue", key=issue_key, transition=transition_name)

        # Get available transitions
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self._base_url}/issue/{issue_key}/transitions",
                auth=self._auth,
            )
            response.raise_for_status()

            transitions = response.json().get("transitions", [])
            transition_id = None

            for t in transitions:
                if t["name"].lower() == transition_name.lower():
                    transition_id = t["id"]
                    break

            if not transition_id:
                logger.warning(
                    "Transition not found",
                    key=issue_key,
                    transition=transition_name,
                    available=[t["name"] for t in transitions],
                )
                return False

            # Perform transition
            response = await client.post(
                f"{self._base_url}/issue/{issue_key}/transitions",
                auth=self._auth,
                headers={"Content-Type": "application/json"},
                json={"transition": {"id": transition_id}},
            )
            response.raise_for_status()

            logger.info("Transitioned issue", key=issue_key, to=transition_name)
            return True

    @async_retry(max_attempts=2)
    async def get_projects(self) -> list[dict[str, Any]]:
        """Get list of accessible Jira projects.

        Returns:
            List of projects
        """
        logger.info("Fetching Jira projects")

        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self._base_url}/project",
                auth=self._auth,
            )
            response.raise_for_status()

            projects = response.json()
            logger.info("Fetched projects", count=len(projects))
            return projects


# Singleton instance
jira_service = JiraService()
